name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]

      - name: Ruff
        run: ruff check .

      - name: Black
        run: black --check .

      - name: isort
        run: isort --check-only .

      - name: Mypy
        run: mypy .

      - name: Unit tests
        run: pytest -m "not contract and not e2e"

      - name: Contract tests
        run: pytest -m contract

      - name: End-to-end tests
        run: pytest -m e2e
